### ISSUE TITLE
 'Lovasz_softmax' is not defined

### ISSUE THREAD

**Issue by amc-nu** [TiagoCortinhal/SalsaNext#3]
When trying to train I get the following error:
```
Traceback (most recent call last):
  File "./train.py", line 143, in <module>
    trainer = Trainer(ARCH, DATA, FLAGS.dataset, FLAGS.log, FLAGS.pretrained,FLAGS.model)
  File "../../tasks/semantic/modules/trainer.py", line 137, in __init__
    self.ls = Lovasz_softmax(ignore=0).to(self.device)
NameError: name 'Lovasz_softmax' is not defined
```

**Comment by TiagoCortinhal** [comment]
Thank you for noticing it! 

I added the missing files.
